version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  disable: true

brews:
  - repository:
      owner: yasomaru
      name: homebrew-tap
      token: "{{ .Env.GH_PAT }}"
    homepage: https://github.com/yasomaru/git-wt
    description: A smarter way to manage git worktrees
    license: MIT
    install: |
      bin.install "git-wt"
    test: |
      system "#{bin}/git-wt", "version"

release:
  github:
    owner: yasomaru
    name: git-wt
  draft: false
  prerelease: auto
